samples: config/samples.tsv

units: config/units.tsv

experiments: config/experiments.yaml

igv_report:
  activate: false

ref:
  # Number of chromosomes to consider for calling.
  # The first n entries of the FASTA will be considered.
  n_chromosomes: 25
  # Ensembl species name
  species: homo_sapiens
  # Ensembl release
  release: 100
  # Genome build
  build: GRCh38

## quality control
qc:
  activate: false

## methylation calling
meth:
  activate: true
  
## dmr calling
dmrs:
  metilene:
    activate: true
    min_cpg: 3
    min_diff: 0.1
  experiments:
    plasma_vs_healthy_plasma:
      case:
        - NSCLC-stage_IV_Plasma_Long
        - NSCLC-stage_IV_Plasma_Short
        - NSCLC-stage_I-III_Plasma_Resected
        - PDAC_Plasma_Long
        - PDAC_Plasma_Short
        - PDAC_Plasma_ND
        - CRC_Plasma_Short
        - CRC_Plasma_Long
        - Melanoma_Plasma_Short
        - Melanoma_Plasma_Long
      control:
        - Healthy_Plasma
    tumor_vs_healthy_tissue:
      case:
        - Lung_Tumor_Stage_I-III_Tissue_Resected
      control:
        - Non-tumor_lung_Tissue_Resected
    NSCLC-stage_IV_Plasma_long_vs_short:
      case:
        - NSCLC-stage_IV_Plasma_Long
      control:
        - NSCLC-stage_IV_Plasma_Short
    PDAC_Plasma_long_vs_short:
      case:
        - PDAC_Plasma_Long
      control:
        - PDAC_Plasma_Short
    CRC_Plasma_long_vs_short:
      case:
        - CRC_Plasma_Long
      control:
        - CRC_Plasma_Short
    Melanoma_long_vs_short:
      case:
        - Melanoma_Plasma_Long
      control:
        - Melanoma_Plasma_Short

## pca
pca:
  activate: false


params:
  cutadapt: "-m 10"
